<?php
/**
 * @file
 * Drupal data portal module -- provides backend for javascript web application.
 */

include 'inc/filesystem.inc';

/**
 * Implements hook_menu().
 */
function data_portal_menu() {
	$items = array();

	// @TODO find a way to deal with url arguments so that Drupal can still
	// read them with unknown path settings.

	// This currently can't be set from the administrative menu so will
	// always be set to data/portal
	$page_path = variable_get('data_portal_page_path', 'data/portal');

	// Main data portal page that web app is rendered on.
	$items[$page_path] = array(
		'title' => 'Data Portal',
		'description' => t('Web portal data collection'),
		'page callback' => 'data_portal_page_gen',
		'access arguments' => array('access data portal'),
	  'type' => MENU_NORMAL_ITEM);
	// Module configuration menu.
	$items['admin/config/data-portal'] = array(
		'title' => 'Data Portal Settings',
		'description' => t('Configuration for the data portal module'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('data_portal_config'),
		'access arguments' => array('access data portal'),
	  'type' => MENU_NORMAL_ITEM);
	// XHR interface for requesting directory listing.
	$items[$page_path . '/update/%'] = array(
		'title' => 'Data Portal Update',
		'page callback' => 'data_portal_ajax_page',
		'page arguments' => array(3),
		'access arguments' => array('access data portal'),
	  'type' => MENU_CALLBACK);
	// XHR interface for requesting data.
	$items[$page_path . '/get-data/%/%'] = array(
		'title' => 'Data Portal Get Image',
		'page callback' => 'data_portal_get_data',
		'page arguments' => array(3, 4),
		'access arguments' => array('access data portal'),
	  'type' => MENU_CALLBACK);
	return($items);
}
/**
 * Config form for Data Portal settings.
 */
function data_portal_config() {
	// Filesystem path that the module crawls -- set by user or default to '/'.
	$fs_path = variable_get('data_portal_fs_path', '/');
	// Path for data portal to be rendered on. Defaults to '/data/portal'.
	$page_path = variable_get('data_portal_page_path', '/data/portal');
	// Gets time that the db file was last updated. Helps determine whether data crawl has finished.
	$ft = 0;
	$disabled = FALSE;
	$ft = filemtime(drupal_get_path('module', 'data_portal') . '/db/dir_db.csv');
	if(time() - $ft >= 60) { //  If file was last updated more than 1 minute ago, datacrawl has completed.
		drupal_set_message('Filesystem crawl complete. You can now run a database update!');
		$disabled = FALSE;
	} else {
		drupal_set_message('Filesystem crawl still running. You can run the database update when crawling is complete');
		$disabled = TRUE;
	}
	$form = array(); // Holds form for rendering by drupal_get_form.

	// Filesystem path to crawl.
	$form['data_portal_fs_path'] = array(
		'#type' => 'textfield',
		'#default_value' => $fs_path);
	/*Customizable display path disabled for now due to menu argument placement issue.
	$form['data_portal_page_path'] = array(
		'#type' => 'textfield',
		'#default_value' => $page_path);*/
	$form['run_cec_data_up'] = array(
		'#type' => 'submit',
		'#value' => 'Run Data Update',
		'#submit' => array('data_portal_db_up'),
		'#disabled' => $disabled);
	$form['recrawl'] = array(
		'#type' => 'submit',
		'#value' => 'Recrawl',
		'#submit' => array('data_portal_run_recrawl'));

	// Saves form input and renders form.
	return(system_settings_form($form));
}

function data_portal_run_recrawl() {
	// Data path to crawl.
	$fs_path = variable_get('data_portal_fs_path', '/');
	$module = drupal_get_path('module', 'data_portal');
	// Save currend working directory to return to once find has been executed.
	$site_root = getcwd();
	// Change directory to data dir.
	chdir($fs_path);
	// Find all files in data path (set in Data Portal Admin settings).
	exec("find . > $site_root/$module/db/dir_db.csv &");
	chdir($site_root);
}

function data_portal_db_up() {
	background_process_start('data_portal_db_up_process');
}

function data_portal_db_up_process() {
	$f = fopen(drupal_get_path('module', 'data_portal') . '/db/dir_db.csv', 'r');
	db_delete('data_portal_data')->execute();
	// Create new filesystem.
	$fs = new FS();
	// Gets each file and directory in the current path split by '/'.
	while(($line = fgetcsv($f, 4000, '/')) != FALSE) {
		// Removing '.'' from beginning of path.
		array_shift($line);
		$cwd = array();
		// For every directory/file name in the path with the key value as its directory level.
		foreach($line as $key=>$dir) {
			$cwd[] = $dir;
			$fs->add_path($cwd);
		}
	}
}

function data_portal_pull_dirs($dir_id, $find_col) {
	$query = db_select('data_portal_data','d');
	// Ged file id, file's parent id and title of the file.
	$query->fields('d',array('id','pid','ppid','title','path'))
	// On first view, we will show directories starting at level 4.
		  ->condition($find_col,$dir_id,'=');
	$results = $query->execute();
	return $results;
}

function data_portal_ajax_page($dir_id) {
	if(isset($dir_id)) {
		$results = data_portal_pull_dirs($dir_id, 'pid');
		$data = array();
		while($record = $results->fetchAssoc()) {
			$fileType = preg_match('/^.*\.(.*?)$/i', $record['title'], $ft);
			if(!isset($ft[1])) {
				$type = 'directory';
			} else {
				$type = $ft[1];
			}
			$record['type'] = $type;
		    $data['items'][] = $record;
		    $data['pid'] = $record['pid'];
		    $data['ppid'] = $record['ppid'];
		}

		$pathResult = data_portal_pull_dirs($dir_id, 'id');

		while($r = $pathResult->fetchAssoc()) {
			$data['path'] = explode('/',$r['path']);
		}

		// Send current filesystem level objects to app Model.
		print(json_encode($data));
	} else {
		print("You haven't requested a directory id");
	}
}

function data_portal_get_image($file, $method, &$header) {
	switch($method) {
		case 'ajax':
			$header = "";
			$image = theme(
				'image',
				array(
					'path' => '/data/portal/get-data/' . $file['id'] . '/resource',
					'attributes' => array(
						'class' =>  'file-' . $file['ext'] . ' file-' . $file['id'],
						'id' => $file['title'],
					),
					'title' => $file['title'],
				)
			);
			return $image;
		case 'resource':
			$file = file_get_contents($file['path']);
			$header = 'Content-Disposition: application; filename="'.$file['title'].'"';
			return $file;
		default:
			return "Method not defined.";
	}
}

function data_portal_get_text($file, $method, &$header) {
	$header = "Content-Type: plain/text";
	return file_get_contents($file['path']);
}

function data_portal_data_type_handler() {
	$items = array();
	$items['plain_txt'] = array(
		'callback' => 'data_portal_get_text',
		'title' => 'Text',
		'ext' => array(
			'txt',
		),
	);
	$items['image'] = array(
		'callback' => 'data_portal_get_image',
		'title' => 'Image',
		'ext' => array(
			'jpg',
			'jpeg',
			'png',
			'gif',
			'tiff',
			'tiff',
			'gtif',
		),
	);
	$items['default'] = array(
		'callback' => 'data_portal_get_text',
		'title' => 'Text',
		'ext' => array(),
	);
	return $items;
}

function data_portal_get_data($id, $method) {
	if(isset($id)) {
		// Will hold header for rendering file.
		$header;
		// Data to render;
		$rendered_file;
		// File hasn't been handled by callback yet.
		$handled = FALSE;
		// Invoke module hooks.
		$callbacks = module_invoke_all('data_type_handler');
		$request = db_select('data_portal_data','d')
			// Ged file id, file's parent id and title of the file.
			->fields('d',array('id','path','title','ext'))
			// On first view, we will show directories starting at level 4.
			->condition('id',$id,'=')
			->range(0,1)
			->execute()
			->fetchAssoc();
		// Root path to user defined data folder.
		$fs_path = variable_get('data_portal_fs_path', '/');
		$request['path'] = $fs_path . $request['path'];
		foreach($callbacks as $callback) {
			// Does this this callback handle the file extension?
			if(in_array($request['ext'], $callback['ext'])) {
				$rendered_file = call_user_func_array($callback['callback'], array($request, $method, &$header));
				$handled = TRUE;
			}
		}
		if(!$handled) {
			$rendered_file = call_user_func_array($callbacks['default']['callback'], array($request, $method, &$header));
		}
		header($header);
		print($rendered_file);
	}
}

function data_portal_page_gen() {
	global $base_url;
	$module_path = $base_url . '/' . drupal_get_path('module', 'data_portal') . '/';
	// Select biogeog data portal db containing directory heirarchy.
	$query = db_select('data_portal_data','d');
	// Ged file id, file's parent id and title of the file.
	$query->fields('d',array('id','pid','title'))
	// On first view, we will show directories starting at level 4.
		  ->condition('pid',4,'=');
	$results = $query->execute();
	$data = array();
	// Run db query for initial data load in app.
	while($record = $results->fetchAssoc()) {
		dsm($record);
		$fileType = preg_match('/^.*\.(.*?)$/i', $record['title'], $ft);
		if(!isset($ft[1])) {
			$type = 'directory';
		} else {
			$type = 'file';
		}
		$record['type'] = $type;
        $data[] = $record;
    }
    // Add javascript app files and dependencies.
    drupal_add_library('system', 'ui.draggable');
    drupal_add_js($module_path . 'js/lib/handlebars.js');
    drupal_add_js($module_path . 'js/lib/underscore-min.js');
    drupal_add_js($module_path . 'js/lib/backbone-min.js');
    drupal_add_js($module_path . 'js/lib/antiscroll.js');
    drupal_add_js($module_path . 'js/Model.js');
    drupal_add_js($module_path . 'js/View.js');
    drupal_add_js($module_path . 'js/Controller.js');
    drupal_add_js($module_path . 'js/app.js');

    // Send current filesystem level objects to app Model.
	drupal_add_js(array('cec-data' => $data, 'path' => $module_path, 'menu' => $_GET['q']), 'setting');
	// Render web app using theme template
	$page = theme('data_portal_template');
	return($page);
}
function data_portal_permission() {
	$items = array();
	$items['access data portal'] = array(
		'title' => 'Access Data Portal Content',
		'description' => t('Access content from the biogeog data portal'));
	return($items);
}
function data_portal_theme() {
	$themes = array(
		'data_portal_template' => array(
			'template' => 'data_portal_template',
		),
	);
	return($themes);
}
